CREATE TABLE clients (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL
);

CREATE TYPE "contact_type" AS ENUM (
	'PHONE',
	'EMAIL'
);

CREATE TABLE contacts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          type VARCHAR(50) NOT NULL,
                          value VARCHAR(255) NOT NULL,
                          client_id BIGINT,
                          FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);
